server:
  port: 8121
spring:
  application:
    name: service-client-code
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.algou.com:3306/lagou?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
  cloud:
    nacos:
      discovery:
        # 配置Nacos sercer地址
        server-addr: 12.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
