server:
  port: 8001
spring:
  application:
    name: cloud-eureka-server #应用名称，会在Eureka中作为服务的id标识
eureka:
  instance:
    hostname: cloud.eureka.serverA
  client:
    service-url:
      # 配置客户端与EurekaServer交互的地址，如果是集群，也需要写其他Server的地址
      defaultZone: http://cloud.eureka.serverB:8002/eureka/
    # 配置是否将当前服务注册到eureka中,如果只有一台Eureka Server的话，自己本身就是
    # 注册中心，故不需要注册到Server，也不需要发现其他服务。
    # 在配置成集群的情况下，可以在集群的其他节点中注册本服务
    register-with-eureka: true
    fetch-registry: true
