server:
  port: 8201
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes: # 路由配置可以有多个
        - id: service-user-router  # 我们自定义的路由ID，保持唯一
          uri: http://127.0.0.1:8111  # 目标服务器地址，动态路由：uri配置的应该是一个服务名称，而不应该是一个具体的服务实例地址
          predicates: #断言：路由条件，predicate接受一个输入参数，返回一个boolean结果。
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: service-email-router
          uri: http://127.0.0.1:8131  # 目标服务器地址，动态路由：uri配置的应该是一个服务名称，而不应该是一个具体的服务实例地址
          predicates: #断言：路由条件，predicate接受一个输入参数，返回一个boolean结果。
            - Path=/api/email/**
          filters:
            - StripPrefix=1
        - id: service-code-router  # 我们自定义的路由ID，保持唯一
          uri: http://127.0.0.1:8121  # 目标服务器地址，动态路由：uri配置的应该是一个服务名称，而不应该是一个具体的服务实例地址
          predicates: #断言：路由条件，predicate接受一个输入参数，返回一个boolean结果。
            - Path=/api/code/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        # 配置Nacos sercer地址
        server-addr: 127.0.0.1:8848



